AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  Gateway:
    Type: AWS::Serverless::HttpApi

  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      Tracing: Active
      CodeUri: ./a
      Runtime: go1.x
      Description: Tracing test
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            ApiId: !Ref Gateway
            Path: /{proxy+}
            Method: ANY
      Handler: main
    Metadata:
      BuildMethod: makefile

Outputs:
  GatewayEndPoint:
    Value: !Sub "https://${Gateway}.execute-api.${AWS::Region}.amazonaws.com/"
  MainFunctionLogs:
    Value: !Sub "sam logs --name ${MainFunction} --region ${AWS::Region} --tail"
